version: "2"

linters:
  enable:
    - loglinter
  settings:
    custom:
      loglinter:
        type: "module"
        description: "checks log messages"
        settings:
          custom-patterns:
            - "my_custom_secret"