name: CI loglinter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
          cache: true

      - name: Run Tests
        run: go test -v ./pkg/analyzer/...

      - name: Build Standalone Binary
        run: go build -v -o loglinter ./cmd/loglinter/main.go

      - name: Check binary execution
        run: ./loglinter test.go || true